all: compil clean
	
compil:
	pdflatex soutenance.tex; pdflatex soutenance.tex

clean:
	rm soutenance.aux soutenance.fdb_latexmk soutenance.log soutenance.nav soutenance.out soutenance.snm soutenance.synctex.gz soutenance.toc
